# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/yusuk/Desktop/プロジェクト/RS-02/RS-02/RS02_GUI.ui',
# licensing of 'C:/Users/yusuk/Desktop/プロジェクト/RS-02/RS-02/RS02_GUI.ui' applies.
#
# Created: Wed Nov 17 21:00:51 2021
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(686, 520)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(7)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setEnabled(False)
        self.groupBox_6.setMinimumSize(QtCore.QSize(171, 81))
        self.groupBox_6.setMaximumSize(QtCore.QSize(171, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.comboBox_1 = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_1.setEnabled(False)
        self.comboBox_1.setGeometry(QtCore.QRect(10, 20, 69, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_1.setFont(font)
        self.comboBox_1.setEditable(False)
        self.comboBox_1.setObjectName("comboBox_1")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_12.setEnabled(False)
        self.pushButton_12.setGeometry(QtCore.QRect(90, 20, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_13.setEnabled(False)
        self.pushButton_13.setGeometry(QtCore.QRect(10, 50, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_14.setEnabled(False)
        self.pushButton_14.setGeometry(QtCore.QRect(90, 50, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.groupBox_6, 2, 6, 2, 2)
        self.lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1.setMaximumSize(QtCore.QSize(59, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setText("")
        self.lineEdit_1.setReadOnly(True)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.gridLayout.addWidget(self.lineEdit_1, 5, 5, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setMinimumSize(QtCore.QSize(121, 111))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBox_1 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_1.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.checkBox_1.setObjectName("checkBox_1")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 40, 101, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setEnabled(False)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 80, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 60, 101, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.groupBox_2, 5, 1, 3, 1)
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setEnabled(False)
        self.pushButton_1.setMaximumSize(QtCore.QSize(83, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 0, 6, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setEnabled(False)
        self.groupBox_4.setMinimumSize(QtCore.QSize(61, 111))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_10.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.radioButton_10.setChecked(True)
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_11.setGeometry(QtCore.QRect(10, 40, 61, 16))
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_12.setGeometry(QtCore.QRect(10, 60, 61, 16))
        self.radioButton_12.setObjectName("radioButton_12")
        self.gridLayout.addWidget(self.groupBox_4, 5, 3, 3, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(18, 38))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 4, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setMaximumSize(QtCore.QSize(83, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 7, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(171, 171))
        self.groupBox_5.setMaximumSize(QtCore.QSize(171, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_9.setEnabled(False)
        self.pushButton_9.setGeometry(QtCore.QRect(90, 80, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 20, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_6.setEnabled(False)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 50, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_7.setEnabled(False)
        self.pushButton_7.setGeometry(QtCore.QRect(90, 50, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setGeometry(QtCore.QRect(90, 20, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_8.setEnabled(False)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 80, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_11.setEnabled(False)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 140, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 110, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_10.setEnabled(False)
        self.pushButton_10.setGeometry(QtCore.QRect(90, 110, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.groupBox_5, 1, 6, 1, 2)
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setMaximumSize(QtCore.QSize(18, 38))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 5, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(18, 38))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 7, 4, 1, 1)
        self.groupBox_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_1.setMinimumSize(QtCore.QSize(71, 111))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_1.setFont(font)
        self.groupBox_1.setObjectName("groupBox_1")
        self.radioButton_1 = QtWidgets.QRadioButton(self.groupBox_1)
        self.radioButton_1.setGeometry(QtCore.QRect(10, 20, 86, 16))
        self.radioButton_1.setChecked(True)
        self.radioButton_1.setObjectName("radioButton_1")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_1)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 40, 86, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_1)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 60, 86, 16))
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.groupBox_1, 5, 0, 3, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(59, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 7, 5, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setEnabled(True)
        self.groupBox_7.setMinimumSize(QtCore.QSize(171, 51))
        self.groupBox_7.setMaximumSize(QtCore.QSize(171, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_15.setEnabled(True)
        self.pushButton_15.setGeometry(QtCore.QRect(10, 20, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_16.setEnabled(True)
        self.pushButton_16.setGeometry(QtCore.QRect(90, 20, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.groupBox_7, 4, 6, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setMinimumSize(QtCore.QSize(131, 111))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 20, 86, 16))
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 40, 86, 16))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_6.setGeometry(QtCore.QRect(10, 60, 86, 16))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_7.setGeometry(QtCore.QRect(70, 20, 61, 16))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_8.setGeometry(QtCore.QRect(70, 40, 61, 16))
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_9.setGeometry(QtCore.QRect(70, 60, 61, 16))
        self.radioButton_9.setObjectName("radioButton_9")
        self.gridLayout.addWidget(self.groupBox_3, 5, 2, 3, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(59, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 6, 5, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setEnabled(True)
        self.groupBox_8.setMinimumSize(QtCore.QSize(171, 101))
        self.groupBox_8.setMaximumSize(QtCore.QSize(171, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_17.setEnabled(True)
        self.pushButton_17.setGeometry(QtCore.QRect(80, 70, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_4.setGeometry(QtCore.QRect(70, 20, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_5.setGeometry(QtCore.QRect(70, 40, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_8)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_8)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.groupBox_8, 5, 6, 3, 2)
        self.plainTextEdit_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_1.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.plainTextEdit_1.setFont(font)
        self.plainTextEdit_1.setAutoFillBackground(False)
        self.plainTextEdit_1.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainTextEdit_1.setReadOnly(False)
        self.plainTextEdit_1.setObjectName("plainTextEdit_1")
        self.gridLayout.addWidget(self.plainTextEdit_1, 0, 0, 3, 6)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setAutoFillBackground(False)
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setBackgroundVisible(False)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout.addWidget(self.plainTextEdit_2, 3, 0, 2, 6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 686, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "RS-02 V1.0", None, -1))
        self.groupBox_6.setTitle(QtWidgets.QApplication.translate("MainWindow", "SERIAL", None, -1))
        self.pushButton_12.setText(QtWidgets.QApplication.translate("MainWindow", "PORTS", None, -1))
        self.pushButton_13.setText(QtWidgets.QApplication.translate("MainWindow", "D CON", None, -1))
        self.pushButton_14.setText(QtWidgets.QApplication.translate("MainWindow", "D DIS", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "SWITCH", None, -1))
        self.checkBox_1.setText(QtWidgets.QApplication.translate("MainWindow", "ONE CYCLE", None, -1))
        self.checkBox_2.setText(QtWidgets.QApplication.translate("MainWindow", "SINGLE BLOCK", None, -1))
        self.checkBox_3.setText(QtWidgets.QApplication.translate("MainWindow", "DEBUG", None, -1))
        self.pushButton_1.setText(QtWidgets.QApplication.translate("MainWindow", "RUN", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "RAPID", None, -1))
        self.radioButton_10.setText(QtWidgets.QApplication.translate("MainWindow", "25", None, -1))
        self.radioButton_11.setText(QtWidgets.QApplication.translate("MainWindow", "50", None, -1))
        self.radioButton_12.setText(QtWidgets.QApplication.translate("MainWindow", "100", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Y :", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("MainWindow", "STOP", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("MainWindow", "DOBOT", None, -1))
        self.pushButton_9.setText(QtWidgets.QApplication.translate("MainWindow", "Z-", None, -1))
        self.pushButton_4.setText(QtWidgets.QApplication.translate("MainWindow", "X+", None, -1))
        self.pushButton_6.setText(QtWidgets.QApplication.translate("MainWindow", "Y+", None, -1))
        self.pushButton_7.setText(QtWidgets.QApplication.translate("MainWindow", "Y-", None, -1))
        self.pushButton_5.setText(QtWidgets.QApplication.translate("MainWindow", "X-", None, -1))
        self.pushButton_8.setText(QtWidgets.QApplication.translate("MainWindow", "Z+", None, -1))
        self.pushButton_11.setText(QtWidgets.QApplication.translate("MainWindow", "POSITION", None, -1))
        self.pushButton_3.setText(QtWidgets.QApplication.translate("MainWindow", "HOME", None, -1))
        self.pushButton_10.setText(QtWidgets.QApplication.translate("MainWindow", "WRITE", None, -1))
        self.label_1.setText(QtWidgets.QApplication.translate("MainWindow", "X :", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Z :", None, -1))
        self.groupBox_1.setTitle(QtWidgets.QApplication.translate("MainWindow", "MODE", None, -1))
        self.radioButton_1.setText(QtWidgets.QApplication.translate("MainWindow", "EDIT", None, -1))
        self.radioButton_2.setText(QtWidgets.QApplication.translate("MainWindow", "AUTO", None, -1))
        self.radioButton_3.setText(QtWidgets.QApplication.translate("MainWindow", "JOG", None, -1))
        self.groupBox_7.setTitle(QtWidgets.QApplication.translate("MainWindow", "FILE", None, -1))
        self.pushButton_15.setText(QtWidgets.QApplication.translate("MainWindow", "OPEN", None, -1))
        self.pushButton_16.setText(QtWidgets.QApplication.translate("MainWindow", "SAVE", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "OVERRIDE", None, -1))
        self.radioButton_4.setText(QtWidgets.QApplication.translate("MainWindow", "0.1mm", None, -1))
        self.radioButton_5.setText(QtWidgets.QApplication.translate("MainWindow", "1mm", None, -1))
        self.radioButton_6.setText(QtWidgets.QApplication.translate("MainWindow", "5mm", None, -1))
        self.radioButton_7.setText(QtWidgets.QApplication.translate("MainWindow", "10mm", None, -1))
        self.radioButton_8.setText(QtWidgets.QApplication.translate("MainWindow", "20mm", None, -1))
        self.radioButton_9.setText(QtWidgets.QApplication.translate("MainWindow", "30mm", None, -1))
        self.groupBox_8.setTitle(QtWidgets.QApplication.translate("MainWindow", "COUNTER", None, -1))
        self.pushButton_17.setText(QtWidgets.QApplication.translate("MainWindow", "RESET", None, -1))
        self.lineEdit_4.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.lineEdit_5.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "COUNT", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "NG", None, -1))

