# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'RS02_GUI.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGridLayout,
    QGroupBox, QLabel, QLineEdit, QMainWindow,
    QMenuBar, QPlainTextEdit, QPushButton, QRadioButton,
    QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(845, 621)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(840, 0))
        font = QFont()
        font.setPointSize(7)
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setMinimumSize(QSize(171, 101))
        self.groupBox_3.setMaximumSize(QSize(171, 16777215))
        font1 = QFont()
        font1.setPointSize(9)
        self.groupBox_3.setFont(font1)
        self.pushButton_6 = QPushButton(self.groupBox_3)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setEnabled(True)
        self.pushButton_6.setGeometry(QRect(80, 70, 71, 23))
        self.pushButton_6.setFont(font1)
        self.lineEdit_4 = QLineEdit(self.groupBox_3)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(70, 20, 81, 20))
        self.lineEdit_4.setFont(font1)
        self.lineEdit_4.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_5 = QLineEdit(self.groupBox_3)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(70, 40, 81, 20))
        self.lineEdit_5.setFont(font1)
        self.lineEdit_5.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_5.setReadOnly(True)
        self.label_4 = QLabel(self.groupBox_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 20, 51, 16))
        self.label_4.setFont(font1)
        self.label_5 = QLabel(self.groupBox_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 40, 51, 16))
        self.label_5.setFont(font1)

        self.gridLayout.addWidget(self.groupBox_3, 3, 2, 1, 1)

        self.groupBox_7 = QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setEnabled(True)
        self.groupBox_7.setMinimumSize(QSize(171, 51))
        self.groupBox_7.setMaximumSize(QSize(171, 16777215))
        self.groupBox_7.setFont(font1)
        self.pushButton_4 = QPushButton(self.groupBox_7)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setEnabled(True)
        self.pushButton_4.setGeometry(QRect(10, 50, 71, 23))
        self.pushButton_4.setFont(font1)
        self.pushButton_5 = QPushButton(self.groupBox_7)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setEnabled(True)
        self.pushButton_5.setGeometry(QRect(90, 50, 71, 23))
        self.pushButton_5.setFont(font1)
        self.pushButton_1 = QPushButton(self.groupBox_7)
        self.pushButton_1.setObjectName(u"pushButton_1")
        self.pushButton_1.setEnabled(False)
        self.pushButton_1.setGeometry(QRect(10, 20, 71, 23))
        self.pushButton_1.setMaximumSize(QSize(83, 23))
        self.pushButton_1.setFont(font1)
        self.pushButton_2 = QPushButton(self.groupBox_7)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QRect(90, 20, 71, 23))
        self.pushButton_2.setMaximumSize(QSize(83, 23))
        self.pushButton_2.setFont(font1)
        self.pushButton_3 = QPushButton(self.groupBox_7)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setEnabled(True)
        self.pushButton_3.setGeometry(QRect(90, 80, 71, 23))
        self.pushButton_3.setFont(font1)

        self.gridLayout.addWidget(self.groupBox_7, 3, 3, 1, 1)

        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setMinimumSize(QSize(121, 111))
        self.groupBox_2.setFont(font1)
        self.checkBox_1 = QCheckBox(self.groupBox_2)
        self.checkBox_1.setObjectName(u"checkBox_1")
        self.checkBox_1.setGeometry(QRect(10, 20, 121, 16))
        self.checkBox_2 = QCheckBox(self.groupBox_2)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(10, 40, 141, 16))
        self.comboBox_1 = QComboBox(self.groupBox_2)
        self.comboBox_1.setObjectName(u"comboBox_1")
        self.comboBox_1.setEnabled(False)
        self.comboBox_1.setGeometry(QRect(10, 80, 101, 22))
        self.comboBox_1.setFont(font1)
        self.comboBox_1.setEditable(False)
        self.checkBox_3 = QCheckBox(self.groupBox_2)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(10, 60, 81, 16))

        self.gridLayout.addWidget(self.groupBox_2, 3, 1, 1, 1)

        self.groupBox_1 = QGroupBox(self.centralwidget)
        self.groupBox_1.setObjectName(u"groupBox_1")
        self.groupBox_1.setMinimumSize(QSize(71, 111))
        self.groupBox_1.setFont(font1)
        self.radioButton_1 = QRadioButton(self.groupBox_1)
        self.radioButton_1.setObjectName(u"radioButton_1")
        self.radioButton_1.setGeometry(QRect(10, 20, 86, 16))
        self.radioButton_1.setChecked(True)
        self.radioButton_2 = QRadioButton(self.groupBox_1)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(10, 40, 86, 16))

        self.gridLayout.addWidget(self.groupBox_1, 3, 0, 1, 1)

        self.plainTextEdit_2 = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setObjectName(u"plainTextEdit_2")
        self.plainTextEdit_2.setEnabled(True)
        font2 = QFont()
        font2.setPointSize(12)
        self.plainTextEdit_2.setFont(font2)
        self.plainTextEdit_2.setAutoFillBackground(False)
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setBackgroundVisible(False)

        self.gridLayout.addWidget(self.plainTextEdit_2, 2, 0, 1, 4)

        self.plainTextEdit_1 = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_1.setObjectName(u"plainTextEdit_1")
        self.plainTextEdit_1.setMinimumSize(QSize(0, 350))
        font3 = QFont()
        font3.setPointSize(18)
        font3.setBold(True)
        self.plainTextEdit_1.setFont(font3)
        self.plainTextEdit_1.setAutoFillBackground(False)
        self.plainTextEdit_1.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.plainTextEdit_1.setReadOnly(False)

        self.gridLayout.addWidget(self.plainTextEdit_1, 0, 0, 2, 4)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 845, 18))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"RS-02 V1.0", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"COUNTER", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"RESET", None))
        self.lineEdit_4.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.lineEdit_5.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"COUNT", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"NG", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"CONTROL", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"OPEN", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"SAVE", None))
        self.pushButton_1.setText(QCoreApplication.translate("MainWindow", u"RUN", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"STOP", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"PORTS", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"SWITCH", None))
        self.checkBox_1.setText(QCoreApplication.translate("MainWindow", u"ONE CYCLE", None))
        self.checkBox_2.setText(QCoreApplication.translate("MainWindow", u"SINGLE BLOCK", None))
        self.checkBox_3.setText(QCoreApplication.translate("MainWindow", u"DEBUG", None))
        self.groupBox_1.setTitle(QCoreApplication.translate("MainWindow", u"MODE", None))
        self.radioButton_1.setText(QCoreApplication.translate("MainWindow", u"EDIT", None))
        self.radioButton_2.setText(QCoreApplication.translate("MainWindow", u"AUTO", None))
    # retranslateUi

